name: CI

on:
  push:
    branches:
      - dev

jobs:
  test-macos:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: build
        run: cmake -B build && make -C build
      - name: test
        run: ./build/test_all
